#!/bin/bash
#SBATCH --image docker:nersc/lammps_lite:23.08
#SBATCH -C cpu
#SBATCH -t 00:30:00
#SBATCH -J LAMMPS_CPU
#SBATCH -o output
#SBATCH -A m3278
#SBATCH -N 1
#SBATCH --ntasks-per-node=128
#SBATCH -q debug

exe=lmp
input="fix.lammps" 

#export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK
export OMP_NUM_THREADS=1
export OMP_PROC_BIND=spread
export OMP_PLACES=threads

command="srun --cpu-bind=cores --module mpich shifter lmp -in $input"

echo $command

$command
